### ISSUE TITLE
Qualitative (discrete) colormaps are seen as continuous

### ISSUE THREAD

**Issue by sebbelese** [derherrg/js-colormaps#1]
I know that this is an old project, but I found it useful to display colormaps in my application. 

However, qualitative colormaps are different than the matplotlib ones. While they should be continuous, it appears that they are actually linearly interpolated:

JS:
![image](https://user-images.githubusercontent.com/16559668/134931350-7f669292-d4b6-4b1a-8a7a-f7395298e200.png)

Matplotlib:
![image](https://user-images.githubusercontent.com/16559668/134931429-e42b0f0b-3fd0-4a16-b8fe-92fedd8298f0.png)

**Comment by timothygebhard** [comment]
Oops, you're right! Thanks a lot for reporting this, I will try to take a closer look at it in the next couple of days 🙂

**Comment by timothygebhard** [comment]
Hi Sébastien! I just pushed a complete overhaul of the repository, hopefully fixing the bug that you have encountered and making the code easier to use. Please let me know if you still have any issues!
